"""character model

Revision ID: 5851b5fc8dbe
Revises: f768dd23e665
Create Date: 2017-12-05 05:44:22.696767

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '5851b5fc8dbe'
down_revision = 'f768dd23e665'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
