"""character model

Revision ID: 87f3df96f413
Revises: 5851b5fc8dbe
Create Date: 2017-12-05 05:55:14.845431

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '87f3df96f413'
down_revision = '5851b5fc8dbe'
branch_labels = ()
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
